name: Reuseable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to download
        required: true
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Fiels
        run: |
          ls -la
      - name: Output Stuff
        run: |
          echo "Hello World"